// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type AIGenerateReq struct {
	Prompt string `json:"prompt"`
}

type AdminAdjustCreditsReq struct {
	UserId uint64 `json:"userId"`
	Delta  int64  `json:"delta"`
}

type AdminConfigListResp struct {
	List []ConfigItem `json:"list"`
}

type AdminDeleteProductReq struct {
	Id uint64 `path:"id"`
}

type AdminFulfillOrderReq struct {
	OrderId        uint64 `json:"orderId"`
	TrackingNumber string `json:"trackingNumber"`
}

type AdminOrderItem struct {
	Id                uint64 `json:"id"`
	OrderNo           string `json:"orderNo"`
	UserEmail         string `json:"userEmail"`
	ProductId         uint64 `json:"productId"`
	ProductTitle      string `json:"productTitle"`
	ProductType       string `json:"productType"`
	LemonOrderId      string `json:"lemonOrderId"`
	AmountCents       uint64 `json:"amountCents"`
	Currency          string `json:"currency"`
	PaymentStatus     string `json:"paymentStatus"`
	FulfillmentStatus string `json:"fulfillmentStatus"`
	ShippingInfo      string `json:"shippingInfo"`
	TrackingNumber    string `json:"trackingNumber"`
	CustomerNote      string `json:"customerNote"`
	CreatedAt         string `json:"createdAt"`
}

type AdminOrderListReq struct {
	Page              int64  `form:"page,default=1"`
	PageSize          int64  `form:"pageSize,default=20"`
	PaymentStatus     string `form:"paymentStatus,optional"`
	FulfillmentStatus string `form:"fulfillmentStatus,optional"`
}

type AdminOrderListResp struct {
	Total int64            `json:"total"`
	List  []AdminOrderItem `json:"list"`
}

type AdminProductItem struct {
	Id             uint64 `json:"id"`
	Title          string `json:"title"`
	Slug           string `json:"slug"`
	Description    string `json:"description"`
	CoverImage     string `json:"coverImage"`
	PriceCents     uint64 `json:"priceCents"`
	ProductType    string `json:"productType"`
	StockCount     int64  `json:"stockCount"`
	LemonVariantId string `json:"lemonVariantId"`
	CreditsReward  int64  `json:"creditsReward"`
	Status         string `json:"status"`
	SortOrder      int64  `json:"sortOrder"`
	Metadata       string `json:"metadata,optional"`
	CreatedAt      string `json:"createdAt"`
	UpdatedAt      string `json:"updatedAt"`
}

type AdminProductListReq struct {
	Page     int64  `form:"page,default=1"`
	PageSize int64  `form:"pageSize,default=20"`
	Status   string `form:"status,optional"`
	Keyword  string `form:"keyword,optional"`
}

type AdminProductListResp struct {
	Total int64              `json:"total"`
	List  []AdminProductItem `json:"list"`
}

type AdminSaveProductReq struct {
	Id             uint64 `json:"id,optional"`
	Title          string `json:"title"`
	Slug           string `json:"slug"`
	Description    string `json:"description"`
	CoverImage     string `json:"coverImage"`
	PriceCents     uint64 `json:"priceCents"`
	ProductType    string `json:"productType"`
	StockCount     int64  `json:"stockCount,default=-1"`
	LemonVariantId string `json:"lemonVariantId"`
	CreditsReward  int64  `json:"creditsReward,default=0"`
	Status         string `json:"status,default=draft"`
	SortOrder      int64  `json:"sortOrder,default=0"`
	Metadata       string `json:"metadata,optional"`
}

type AdminToggleStatusReq struct {
	Id     uint64 `path:"id"`
	Status string `json:"status"`
}

type AdminUpdateConfigReq struct {
	ConfigKey   string `json:"configKey"`
	ConfigValue string `json:"configValue"`
}

type AdminUploadResp struct {
	Url string `json:"url"`
}

type AdminUserItem struct {
	Id        uint64 `json:"id"`
	Email     string `json:"email"`
	Role      string `json:"role"`
	AvatarUrl string `json:"avatarUrl"`
	Credits   int64  `json:"credits"`
	GoogleId  string `json:"googleId"`
	CreatedAt string `json:"createdAt"`
}

type AdminUserListReq struct {
	Page     int64  `form:"page,default=1"`
	PageSize int64  `form:"pageSize,default=20"`
	Keyword  string `form:"keyword,optional"`
}

type AdminUserListResp struct {
	Total int64           `json:"total"`
	List  []AdminUserItem `json:"list"`
}

type CancelOrderReq struct {
	OrderNo string `path:"orderNo"`
}

type ConfigItem struct {
	ConfigKey   string `json:"configKey"`
	ConfigValue string `json:"configValue"`
	Description string `json:"description"`
}

type CreateOrderCheckoutReq struct {
	ProductId    uint64 `json:"productId"`             // 购买的商品ID
	Quantity     int64  `json:"quantity,default=1"`    // 购买数量(默认1)
	CustomerNote string `json:"customerNote,optional"` // 买家下单备注留言
}

type CreateOrderCheckoutResp struct {
	OrderNo     string `json:"orderNo"`     // 系统生成的唯一订单号 (如 ORD_1718000000_1001)
	CheckoutUrl string `json:"checkoutUrl"` // Lemon Squeezy 专属收银台支付链接
	AmountCents uint64 `json:"amountCents"` // 应付总金额(美分)
}

type GoogleAuthReq struct {
	Code string `json:"code"`
}

type LoginReq struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type LoginResp struct {
	Token    string `json:"token"`
	ExpireAt int64  `json:"expireAt"`
	User     UserVo `json:"user"`
}

type NilResp struct {
}

type RegisterReq struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type StoreProductDetailReq struct {
	Slug string `path:"slug"`
}

type StoreProductItem struct {
	Id             uint64 `json:"id"`
	Title          string `json:"title"`
	Slug           string `json:"slug"`
	Description    string `json:"description"`
	CoverImage     string `json:"coverImage"`
	PriceCents     uint64 `json:"priceCents"`
	ProductType    string `json:"productType"`
	LemonVariantId string `json:"lemonVariantId"`
	CreditsReward  int64  `json:"creditsReward"`
	Metadata       string `json:"metadata,optional"`
}

type StoreProductListResp struct {
	List []StoreProductItem `json:"list"`
}

type UserOrderDetailReq struct {
	OrderNo string `path:"orderNo"`
}

type UserOrderDetailResp struct {
	OrderNo           string `json:"orderNo"`
	ProductId         uint64 `json:"productId"`
	ProductTitle      string `json:"productTitle"`
	Description       string `json:"description"`
	CoverImage        string `json:"coverImage"`
	ProductType       string `json:"productType"`
	AmountCents       uint64 `json:"amountCents"`
	Currency          string `json:"currency"`
	PaymentStatus     string `json:"paymentStatus"`
	FulfillmentStatus string `json:"fulfillmentStatus"`
	ShippingInfo      string `json:"shippingInfo"`   // 买家收件信息快照(JSON)
	TrackingNumber    string `json:"trackingNumber"` // 物流单号
	CustomerNote      string `json:"customerNote"`   // 留言
	CreatedAt         string `json:"createdAt"`
	PaidAt            string `json:"paidAt,optional"`
}

type UserOrderItem struct {
	OrderNo           string `json:"orderNo"`
	ProductId         uint64 `json:"productId"`
	ProductTitle      string `json:"productTitle"`
	CoverImage        string `json:"coverImage"`
	ProductType       string `json:"productType"` // digital / physical
	Quantity          int64  `json:"quantity"`
	AmountCents       uint64 `json:"amountCents"`
	Currency          string `json:"currency"`
	PaymentStatus     string `json:"paymentStatus"`
	FulfillmentStatus string `json:"fulfillmentStatus"`
	TrackingNumber    string `json:"trackingNumber"` // 运单号
	CreatedAt         string `json:"createdAt"`
}

type UserOrderListReq struct {
	Page          int64  `form:"page,default=1"`
	PageSize      int64  `form:"pageSize,default=10"`
	PaymentStatus string `form:"paymentStatus,optional"` // pending(待付) / paid(已付) / refunded(退款)
}

type UserOrderListResp struct {
	Total int64           `json:"total"`
	List  []UserOrderItem `json:"list"`
}

type UserOrderStatusReq struct {
	OrderNo string `path:"orderNo"`
}

type UserOrderStatusResp struct {
	OrderNo           string `json:"orderNo"`
	PaymentStatus     string `json:"paymentStatus"`     // paid / pending
	FulfillmentStatus string `json:"fulfillmentStatus"` // fulfilled / unfulfilled
	CreditsRewarded   int64  `json:"creditsRewarded"`   // 若为虚拟品，充值的点数
}

type UserVo struct {
	Id        uint64 `json:"id"`
	Email     string `json:"email"`
	Role      string `json:"role"`
	AvatarUrl string `json:"avatarUrl"`
	Credits   int64  `json:"credits"`
	CreatedAt string `json:"createdAt"`
}
