// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package handler

import (
	"net/http"

	adminorder "goship/backend/internal/handler/admin/order"
	adminproduct "goship/backend/internal/handler/admin/product"
	adminuser "goship/backend/internal/handler/admin/user"
	storeauth "goship/backend/internal/handler/store/auth"
	storeproduct "goship/backend/internal/handler/store/product"
	storewebhook "goship/backend/internal/handler/store/webhook"
	userorder "goship/backend/internal/handler/user/order"
	userprofile "goship/backend/internal/handler/user/profile"
	"goship/backend/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AdminAuth},
			[]rest.Route{
				{
					// 后台获取订单列表
					Method:  http.MethodGet,
					Path:    "/orders",
					Handler: adminorder.GetAdminOrdersHandler(serverCtx),
				},
				{
					// 后台实物订单发货 (回填运单号)
					Method:  http.MethodPost,
					Path:    "/orders/fulfill",
					Handler: adminorder.FulfillOrderHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1/admin"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AdminAuth},
			[]rest.Route{
				{
					// 后台获取商品列表
					Method:  http.MethodGet,
					Path:    "/products",
					Handler: adminproduct.GetAdminProductsHandler(serverCtx),
				},
				{
					// 后台新增/修改商品
					Method:  http.MethodPost,
					Path:    "/products",
					Handler: adminproduct.SaveAdminProductHandler(serverCtx),
				},
				{
					// 后台删除商品
					Method:  http.MethodDelete,
					Path:    "/products/:id",
					Handler: adminproduct.DeleteProductHandler(serverCtx),
				},
				{
					// 后台上下架切换
					Method:  http.MethodPatch,
					Path:    "/products/:id/status",
					Handler: adminproduct.ToggleProductStatusHandler(serverCtx),
				},
				{
					// 直传 Cloudflare R2 图片
					Method:  http.MethodPost,
					Path:    "/upload",
					Handler: adminproduct.UploadAssetHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1/admin"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AdminAuth},
			[]rest.Route{
				{
					// 后台获取系统全局配置
					Method:  http.MethodGet,
					Path:    "/configs",
					Handler: adminuser.GetSystemConfigsHandler(serverCtx),
				},
				{
					// 后台修改系统全局配置
					Method:  http.MethodPut,
					Path:    "/configs",
					Handler: adminuser.UpdateSystemConfigHandler(serverCtx),
				},
				{
					// 后台查看注册用户列表
					Method:  http.MethodGet,
					Path:    "/users",
					Handler: adminuser.GetAdminUsersHandler(serverCtx),
				},
				{
					// 后台手动增减用户点数
					Method:  http.MethodPost,
					Path:    "/users/credits",
					Handler: adminuser.AdjustUserCreditsHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1/admin"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// Google OAuth 一键登录
				Method:  http.MethodPost,
				Path:    "/google",
				Handler: storeauth.GoogleAuthHandler(serverCtx),
			},
			{
				// 用户邮箱密码登录
				Method:  http.MethodPost,
				Path:    "/login",
				Handler: storeauth.LoginHandler(serverCtx),
			},
			{
				// 用户邮箱密码注册
				Method:  http.MethodPost,
				Path:    "/register",
				Handler: storeauth.RegisterHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/auth"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 获取前台已上架商品列表 (SSR展示)
				Method:  http.MethodGet,
				Path:    "/products",
				Handler: storeproduct.GetStoreProductsHandler(serverCtx),
			},
			{
				// 获取单个商品详情页
				Method:  http.MethodGet,
				Path:    "/products/:slug",
				Handler: storeproduct.GetStoreProductDetailHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/store"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// Lemon Squeezy 支付成功回调通知
				Method:  http.MethodPost,
				Path:    "/lemonsqueezy",
				Handler: storewebhook.LemonSqueezyWebhookHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/webhook"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 前台用户分页查询我的订单列表
				Method:  http.MethodGet,
				Path:    "/orders",
				Handler: userorder.GetMyOrdersHandler(serverCtx),
			},
			{
				// 前台用户查看单个订单详情(含物流与收件地址)
				Method:  http.MethodGet,
				Path:    "/orders/:orderNo",
				Handler: userorder.GetOrderDetailHandler(serverCtx),
			},
			{
				// 前台用户取消未支付的 pending 订单
				Method:  http.MethodPost,
				Path:    "/orders/:orderNo/cancel",
				Handler: userorder.CancelPendingOrderHandler(serverCtx),
			},
			{
				// 前台支付结果轮询(付款跳回后检查是否已到账)
				Method:  http.MethodGet,
				Path:    "/orders/:orderNo/status",
				Handler: userorder.CheckOrderStatusHandler(serverCtx),
			},
			{
				// 【核心】前台用户下单并获取支付收银台链接
				Method:  http.MethodPost,
				Path:    "/orders/checkout",
				Handler: userorder.CreateOrderCheckoutHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1/user"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// AI 流式生成演示 (SSE)
				Method:  http.MethodPost,
				Path:    "/ai/generate",
				Handler: userprofile.AIGenerateHandler(serverCtx),
			},
			{
				// 获取当前登录用户资料与点数
				Method:  http.MethodGet,
				Path:    "/profile",
				Handler: userprofile.GetProfileHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1/user"),
	)
}
