// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameOrder = "orders"

// Order 交易与履约订单表
type Order struct {
	ID                int            `gorm:"column:id;type:bigint(20) unsigned;primaryKey;autoIncrement:true;comment:订单主键ID" json:"id"`                                                                                        // 订单主键ID
	OrderNo           string         `gorm:"column:order_no;type:varchar(64);not null;uniqueIndex:uk_order_no,priority:1;comment:系统内部业务订单号(全局唯一)" json:"order_no"`                                                             // 系统内部业务订单号(全局唯一)
	UserID            int            `gorm:"column:user_id;type:bigint(20) unsigned;not null;index:idx_user_id,priority:1;comment:购买者用户ID" json:"user_id"`                                                                     // 购买者用户ID
	ProductID         int            `gorm:"column:product_id;type:bigint(20) unsigned;not null;index:idx_product_id,priority:1;comment:关联商品ID" json:"product_id"`                                                             // 关联商品ID
	LemonOrderID      string         `gorm:"column:lemon_order_id;type:varchar(64);not null;index:idx_lemon_order_id,priority:1;default:'';comment:Lemon Squeezy官方交易订单ID" json:"lemon_order_id"`                               // Lemon Squeezy官方交易订单ID
	AmountCents       int            `gorm:"column:amount_cents;type:int(10) unsigned;not null;comment:实付总金额(美分)" json:"amount_cents"`                                                                                         // 实付总金额(美分)
	Currency          string         `gorm:"column:currency;type:varchar(8);not null;default:USD;comment:结算币种(默认USD)" json:"currency"`                                                                                         // 结算币种(默认USD)
	PaymentStatus     string         `gorm:"column:payment_status;type:varchar(32);not null;index:idx_payment_status,priority:1;default:pending;comment:支付状态: pending(待支付) / paid(已支付) / refunded(已退款)" json:"payment_status"` // 支付状态: pending(待支付) / paid(已支付) / refunded(已退款)
	FulfillmentStatus string         `gorm:"column:fulfillment_status;type:varchar(32);not null;default:unfulfilled;comment:履约发货状态: unfulfilled(待发货/待开通) / fulfilled(已完成)" json:"fulfillment_status"`                          // 履约发货状态: unfulfilled(待发货/待开通) / fulfilled(已完成)
	ShippingInfo      *string        `gorm:"column:shipping_info;type:json;comment:买家收件信息JSON(姓名、国家代码、详细街道、城市、州/省、邮编、电话)" json:"shipping_info"`                                                                                // 买家收件信息JSON(姓名、国家代码、详细街道、城市、州/省、邮编、电话)
	TrackingNumber    string         `gorm:"column:tracking_number;type:varchar(128);not null;default:'';comment:国际物流快递单号(实物订单发货填写)" json:"tracking_number"`                                                                   // 国际物流快递单号(实物订单发货填写)
	CustomerNote      *string        `gorm:"column:customer_note;type:text;comment:买家下单备注" json:"customer_note"`                                                                                                               // 买家下单备注
	Metadata          *string        `gorm:"column:metadata;type:json;comment:扩展字段: Lemon Squeezy原始Webhook Payload镜像备份" json:"metadata"`                                                                                       // 扩展字段: Lemon Squeezy原始Webhook Payload镜像备份
	CreatedAt         time.Time      `gorm:"column:created_at;type:timestamp;not null;default:CURRENT_TIMESTAMP;<-:create;comment:下单时间" json:"created_at"`                                                                     // 下单时间
	UpdatedAt         time.Time      `gorm:"column:updated_at;type:timestamp;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"updated_at"`                                                                               // 更新时间
	DeletedAt         gorm.DeletedAt `gorm:"column:deleted_at;type:timestamp;comment:软删除时间" json:"deleted_at"`                                                                                                                 // 软删除时间
}

// TableName Order's table name
func (*Order) TableName() string {
	return TableNameOrder
}
