// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameProduct = "products"

// Product 商品与服务表
type Product struct {
	ID             int            `gorm:"column:id;type:bigint(20) unsigned;primaryKey;autoIncrement:true;comment:商品主键ID" json:"id"`                                                                       // 商品主键ID
	Title          string         `gorm:"column:title;type:varchar(128);not null;comment:商品展示名称" json:"title"`                                                                                             // 商品展示名称
	Slug           string         `gorm:"column:slug;type:varchar(128);not null;uniqueIndex:uk_slug,priority:1;comment:SEO友好URL标识(唯一,如 pro-plan 或 cyberpunk-clock)" json:"slug"`                           // SEO友好URL标识(唯一,如 pro-plan 或 cyberpunk-clock)
	Description    *string        `gorm:"column:description;type:text;comment:商品详情介绍(支持Markdown或HTML)" json:"description"`                                                                                 // 商品详情介绍(支持Markdown或HTML)
	CoverImage     string         `gorm:"column:cover_image;type:varchar(255);not null;default:'';comment:商品主图(Cloudflare R2 CDN地址)" json:"cover_image"`                                                   // 商品主图(Cloudflare R2 CDN地址)
	PriceCents     int            `gorm:"column:price_cents;type:int(10) unsigned;not null;comment:售价(以美分为单位, 如 2900 = $29.00)" json:"price_cents"`                                                        // 售价(以美分为单位, 如 2900 = $29.00)
	ProductType    string         `gorm:"column:product_type;type:varchar(32);not null;default:digital;comment:商品属性: digital(虚拟SaaS/点数) / physical(实物/周边)" json:"product_type"`                            // 商品属性: digital(虚拟SaaS/点数) / physical(实物/周边)
	StockCount     int            `gorm:"column:stock_count;type:int(11);not null;default:-1;comment:库存数量: -1表示无限库存(虚拟品), >=0表示实物库存" json:"stock_count"`                                                   // 库存数量: -1表示无限库存(虚拟品), >=0表示实物库存
	LemonVariantID string         `gorm:"column:lemon_variant_id;type:varchar(64);not null;index:idx_lemon_variant,priority:1;default:'';comment:绑定的Lemon Squeezy收银台商品Variant ID" json:"lemon_variant_id"` // 绑定的Lemon Squeezy收银台商品Variant ID
	CreditsReward  int            `gorm:"column:credits_reward;type:int(11);not null;default:0;comment:购买后自动赠送的AI点数(仅对虚拟品生效)" json:"credits_reward"`                                                       // 购买后自动赠送的AI点数(仅对虚拟品生效)
	Status         string         `gorm:"column:status;type:varchar(32);not null;index:idx_status_sort,priority:1;default:draft;comment:上下架状态: draft(草稿) / active(上架) / archived(下架)" json:"status"`       // 上下架状态: draft(草稿) / active(上架) / archived(下架)
	SortOrder      int            `gorm:"column:sort_order;type:int(11);not null;index:idx_status_sort,priority:2;default:0;comment:展示排序权重(越大越靠前)" json:"sort_order"`                                      // 展示排序权重(越大越靠前)
	Metadata       *string        `gorm:"column:metadata;type:json;comment:扩展字段: 实体规格(颜色/尺寸)、SEO关键词、多语言标签等" json:"metadata"`                                                                               // 扩展字段: 实体规格(颜色/尺寸)、SEO关键词、多语言标签等
	CreatedAt      time.Time      `gorm:"column:created_at;type:timestamp;not null;default:CURRENT_TIMESTAMP;<-:create;comment:创建时间" json:"created_at"`                                                    // 创建时间
	UpdatedAt      time.Time      `gorm:"column:updated_at;type:timestamp;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"updated_at"`                                                              // 更新时间
	DeletedAt      gorm.DeletedAt `gorm:"column:deleted_at;type:timestamp;comment:软删除时间" json:"deleted_at"`                                                                                                // 软删除时间
}

// TableName Product's table name
func (*Product) TableName() string {
	return TableNameProduct
}
