// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSystemConfig = "system_configs"

// SystemConfig 全局轻量运行时配置表
type SystemConfig struct {
	ID          int       `gorm:"column:id;type:bigint(20) unsigned;primaryKey;autoIncrement:true;comment:配置主键ID" json:"id"`                             // 配置主键ID
	ConfigKey   string    `gorm:"column:config_key;type:varchar(64);not null;uniqueIndex:uk_config_key,priority:1;comment:配置键名(唯一标识)" json:"config_key"` // 配置键名(唯一标识)
	ConfigValue string    `gorm:"column:config_value;type:text;not null;comment:配置内容值" json:"config_value"`                                              // 配置内容值
	Description string    `gorm:"column:description;type:varchar(255);not null;default:'';comment:配置项说明描述" json:"description"`                           // 配置项说明描述
	CreatedAt   time.Time `gorm:"column:created_at;type:timestamp;not null;default:CURRENT_TIMESTAMP;<-:create;comment:创建时间" json:"created_at"`          // 创建时间
	UpdatedAt   time.Time `gorm:"column:updated_at;type:timestamp;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"updated_at"`                    // 更新时间
}

// TableName SystemConfig's table name
func (*SystemConfig) TableName() string {
	return TableNameSystemConfig
}
