// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameUser = "users"

// User 用户基础信息表
type User struct {
	ID           int            `gorm:"column:id;type:bigint(20) unsigned;primaryKey;autoIncrement:true;comment:用户主键ID" json:"id"`                                        // 用户主键ID
	Email        string         `gorm:"column:email;type:varchar(128);not null;uniqueIndex:uk_email,priority:1;comment:登录邮箱(唯一)" json:"email"`                            // 登录邮箱(唯一)
	PasswordHash string         `gorm:"column:password_hash;type:varchar(255);not null;default:'';comment:Bcrypt加密密码(OAuth用户可为空)" json:"password_hash"`                   // Bcrypt加密密码(OAuth用户可为空)
	Role         string         `gorm:"column:role;type:varchar(32);not null;index:idx_role,priority:1;default:user;comment:角色权限: user(普通用户) / admin(超级管理员)" json:"role"` // 角色权限: user(普通用户) / admin(超级管理员)
	AvatarURL    string         `gorm:"column:avatar_url;type:varchar(255);not null;default:'';comment:用户头像CDN链接" json:"avatar_url"`                                      // 用户头像CDN链接
	Credits      int            `gorm:"column:credits;type:int(11);not null;default:10;comment:AI调用点数/可用额度" json:"credits"`                                               // AI调用点数/可用额度
	GoogleID     string         `gorm:"column:google_id;type:varchar(64);not null;index:idx_google_id,priority:1;default:'';comment:Google OAuth唯一用户标识" json:"google_id"` // Google OAuth唯一用户标识
	Metadata     *string        `gorm:"column:metadata;type:json;comment:扩展字段: 用户画像、偏好设置等" json:"metadata"`                                                               // 扩展字段: 用户画像、偏好设置等
	CreatedAt    time.Time      `gorm:"column:created_at;type:timestamp;not null;default:CURRENT_TIMESTAMP;<-:create;comment:注册时间" json:"created_at"`                     // 注册时间
	UpdatedAt    time.Time      `gorm:"column:updated_at;type:timestamp;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"updated_at"`                               // 更新时间
	DeletedAt    gorm.DeletedAt `gorm:"column:deleted_at;type:timestamp;comment:软删除时间" json:"deleted_at"`                                                                 // 软删除时间
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
